### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by hamedmohammadi** [Kovak/KivEnt#56]
Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
from kivy.graphics.vertex cimport VertexFormat, vertex_attr_t
from kivy.graphics.instructions cimport VertexInstruction, getActiveContext
from kivy.graphics.vbo cimport VBO, VertexBatch
                                   ^
------------------------------------------------------------

kivent_core/cmesh.pyx:4:36: Name 'VertexBatch' not declared in module 'kivy.graphics.vbo'

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.graphics.vertex cimport VertexFormat, vertex_attr_t
from kivy.graphics.instructions cimport VertexInstruction, getActiveContext
from kivy.graphics.vbo cimport VBO, VertexBatch
from kivy.logger import Logger
from kivy.graphics.c_opengl cimport *
from kivy.graphics.context cimport Context, get_context
^
------------------------------------------------------------

kivent_core/cmesh.pyx:7:0: 'kivy/graphics/context.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.graphics.vertex cimport VertexFormat, vertex_attr_t
from kivy.graphics.instructions cimport VertexInstruction, getActiveContext
from kivy.graphics.vbo cimport VBO, VertexBatch
from kivy.logger import Logger
from kivy.graphics.c_opengl cimport *
from kivy.graphics.context cimport Context, get_context
^
------------------------------------------------------------

kivent_core/cmesh.pyx:7:0: 'Context.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.graphics.vertex cimport VertexFormat, vertex_attr_t
from kivy.graphics.instructions cimport VertexInstruction, getActiveContext
from kivy.graphics.vbo cimport VBO, VertexBatch
from kivy.logger import Logger
from kivy.graphics.c_opengl cimport *
from kivy.graphics.context cimport Context, get_context
                                  ^
------------------------------------------------------------

kivent_core/cmesh.pyx:7:35: Name 'Context' not declared in module 'kivy.graphics.context'

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.graphics.vertex cimport VertexFormat, vertex_attr_t
from kivy.graphics.instructions cimport VertexInstruction, getActiveContext
from kivy.graphics.vbo cimport VBO, VertexBatch
from kivy.logger import Logger
from kivy.graphics.c_opengl cimport *
from kivy.graphics.context cimport Context, get_context
^
------------------------------------------------------------

kivent_core/cmesh.pyx:7:0: 'get_context.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.graphics.vertex cimport VertexFormat, vertex_attr_t
from kivy.graphics.instructions cimport VertexInstruction, getActiveContext
from kivy.graphics.vbo cimport VBO, VertexBatch
from kivy.logger import Logger
from kivy.graphics.c_opengl cimport *
from kivy.graphics.context cimport Context, get_context
                                           ^
------------------------------------------------------------

kivent_core/cmesh.pyx:7:44: Name 'get_context' not declared in module 'kivy.graphics.context'

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.graphics.instructions cimport VertexInstruction, getActiveContext
from kivy.graphics.vbo cimport VBO, VertexBatch
from kivy.logger import Logger
from kivy.graphics.c_opengl cimport *
from kivy.graphics.context cimport Context, get_context
from kivy.graphics.shader cimport Shader
^
------------------------------------------------------------

kivent_core/cmesh.pyx:8:0: 'kivy/graphics/shader.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.graphics.instructions cimport VertexInstruction, getActiveContext
from kivy.graphics.vbo cimport VBO, VertexBatch
from kivy.logger import Logger
from kivy.graphics.c_opengl cimport *
from kivy.graphics.context cimport Context, get_context
from kivy.graphics.shader cimport Shader
^
------------------------------------------------------------

kivent_core/cmesh.pyx:8:0: 'Shader.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.graphics.instructions cimport VertexInstruction, getActiveContext
from kivy.graphics.vbo cimport VBO, VertexBatch
from kivy.logger import Logger
from kivy.graphics.c_opengl cimport *
from kivy.graphics.context cimport Context, get_context
from kivy.graphics.shader cimport Shader
                                 ^
------------------------------------------------------------

kivent_core/cmesh.pyx:8:34: Name 'Shader' not declared in module 'kivy.graphics.shader'

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.graphics.vbo cimport VBO, VertexBatch
from kivy.logger import Logger
from kivy.graphics.c_opengl cimport *
from kivy.graphics.context cimport Context, get_context
from kivy.graphics.shader cimport Shader
from kivy.graphics.vbo cimport default_vertex
^
------------------------------------------------------------

kivent_core/cmesh.pyx:9:0: 'default_vertex.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from kivy.graphics.vbo cimport VBO, VertexBatch
from kivy.logger import Logger
from kivy.graphics.c_opengl cimport *
from kivy.graphics.context cimport Context, get_context
from kivy.graphics.shader cimport Shader
from kivy.graphics.vbo cimport default_vertex
                              ^
------------------------------------------------------------

kivent_core/cmesh.pyx:9:31: Name 'default_vertex' not declared in module 'kivy.graphics.vbo'

Error compiling Cython file:
------------------------------------------------------------
...
#         return '<VertexBatch at %x id=%r vertex=%d size=%d mode=%s vbo=%x>' % (
#                 id(self), self.id if self.flags & V_HAVEID else None,
#                 self.elements.count(), self.elements.size(), self.get_mode(),
#                 id(self.vbo))

cdef class CMesh(VertexInstruction):
    ^
------------------------------------------------------------

kivent_core/cmesh.pyx:433:5: 'VertexInstruction' is not declared

Error compiling Cython file:
------------------------------------------------------------
...

    def __dealloc__(self):
        self._obatch.clear_data()
            

    cdef void build(self):
        ^
------------------------------------------------------------

kivent_core/cmesh.pyx:449:9: C method 'build' not previously declared in definition part of extension type

Error compiling Cython file:
------------------------------------------------------------
...
        cdef long vcount = self.vcount
        cdef vsize = batch.vbo.vertex_format.vsize
        cdef long icount = self.icount
        batch.set_data(vertices, <int>(vcount / vsize), indices, <int>icount)

    cdef void apply(self):
        ^
------------------------------------------------------------

kivent_core/cmesh.pyx:460:9: C method 'apply' not previously declared in definition part of extension type

Error compiling Cython file:
------------------------------------------------------------
...
        self._obatch.clear_data()
            

    cdef void build(self):
        cdef float* vertices
        cdef VertexBatch batch = self._obatch
            ^
------------------------------------------------------------

kivent_core/cmesh.pyx:451:13: 'VertexBatch' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

cdef class CMesh(VertexInstruction):
    

    def __init__(self, **kwargs):
        VertexInstruction.__init__(self, **kwargs)
                        ^
------------------------------------------------------------

kivent_core/cmesh.pyx:437:25: undeclared name not builtin: VertexInstruction

Error compiling Cython file:
------------------------------------------------------------
...

    def __init__(self, **kwargs):
        VertexInstruction.__init__(self, **kwargs)
        fmt = kwargs.get('fmt')
        if fmt is not None:
            self.vertex_format = VertexFormat(*fmt)
                                            ^
------------------------------------------------------------

kivent_core/cmesh.pyx:440:45: undeclared name not builtin: VertexFormat

Error compiling Cython file:
------------------------------------------------------------
...
    def __init__(self, **kwargs):
        VertexInstruction.__init__(self, **kwargs)
        fmt = kwargs.get('fmt')
        if fmt is not None:
            self.vertex_format = VertexFormat(*fmt)
            self._obatch = VertexBatch(vbo=VBO(self.vertex_format))
                                     ^
------------------------------------------------------------

kivent_core/cmesh.pyx:441:38: undeclared name not builtin: VertexBatch

Error compiling Cython file:
------------------------------------------------------------
...
        vertices = <float *>self._vertices
        indices = <unsigned short*>self._indices
        cdef long vcount = self.vcount
        cdef vsize = batch.vbo.vertex_format.vsize
        cdef long icount = self.icount
        batch.set_data(vertices, <int>(vcount / vsize), indices, <int>icount)
                              ^
------------------------------------------------------------

kivent_core/cmesh.pyx:458:31: Cannot convert 'float *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        vertices = <float *>self._vertices
        indices = <unsigned short*>self._indices
        cdef long vcount = self.vcount
        cdef vsize = batch.vbo.vertex_format.vsize
        cdef long icount = self.icount
        batch.set_data(vertices, <int>(vcount / vsize), indices, <int>icount)
                                                              ^
------------------------------------------------------------

kivent_core/cmesh.pyx:458:63: Cannot convert 'unsigned short *' to Python object
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    extensions, core_modules)
  File "setup.py", line 54, in build_extensions_for_modules_cython
    return cythonize(ext_list)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 840, in cythonize
    cythonize_one(*args[1:])
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 959, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: kivent_core/cmesh.pyx

**Comment by Kovak** [comment]
This error means that you do not have a compiled kivy inside your PYTHONPATH to be found.

**Comment by hamedmohammadi** [comment]
but @Kovak  i followed your readme carefully look closer to this line please
kivent_core/cmesh.pyx:8:0: 'Shader.pxd' not found
i think something is missing

**Comment by hamedmohammadi** [comment]
my os is ubuntu 14 and i test your installation steps exactly in 2 pc

**Comment by hamedmohammadi** [comment]
@kovak i found the solution there is one line in your readme to re new your terminal and it will erase PYTHONPATH exports we have to wirte them in bashrc to have the permanently :+1:

**Comment by chozabu** [comment]
@hamedmohammadi I probably wrote the relevant part of that readme - it does mention to add them to your .bashrc here https://github.com/Kovak/KivEnt/blob/new_rendering/README.md#build-and-environment-vars right after building cymunk and before giving the export commands.

Still, it sure could be more clear - it could also add kivent_core and kivent_cymunk to PYTHONPATH instead of softlinking.

If you can clariy/improve the setup docs atall, that could be great!

**Comment by hamedmohammadi** [comment]
it's my pleasure dude i will do that at the first moment that i cover whole code give me some time.
it's been long time that i did'nt look your jobs and thank you guys with this improvement . i enjoy from what you've done .:)
